title: Test crowdin sync one
hero_image: images/banner.png
description: default-project-template description again
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: Wat ga je maken
  - title: Wat kun je nu doen?
  - title: Enorm
    completion:
      - internal
